DATA SEGMENT
    DB 100 DUP(?)
DATA ENDS
SSEG SEGMENT
    DB 100 DUP(?)
SSEG ENDS
ESSG SEGMENT
    STRING2  DB 0DH, 0AH, "SMALL ONE:$"	;
ESSG ENDS
CODE SEGMENT
    ASSUME CS:CODE, DS:DATA, SS:SSEG, ES:ESSG;
START:
    MOV AX, DATA;
    MOV DS, AX;
    MOV AX, SSEG;
    MOV SS, AX;
    MOV AX, ESSG;
    MOV ES, AX;

    MOV DX, OFFSET STRING2;
    MOV AH, 09H;
    INT 21H;
    MOV AH, 4CH;
    INT 21H;
CODE ENDS
    END START